# Generated by Django 5.1.1 on 2024-10-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='sem-email@exemplo.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='Nome Não Informado', max_length=255),
            preserve_default=False,
        ),
    ]
