# Generated by Django 5.1.1 on 2024-10-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cliente_user_cliente_email_cliente_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='hora_reserva',
            new_name='hora_entrada',
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_saida',
            field=models.TimeField(default='18:00'),
            preserve_default=False,
        ),
    ]
